microsoft/code-push

- cli/package.json
- cli/script/command-executor.ts
Also added a fix to not let users delete the access key to the local machine otherwise it leads us to a weird behavior where you are not authorized because the access key is removed but can't login because you still have the connection info persisted on disk with an invalid access key.
> Fix to not login from the same machine in CLI

- README.md
Our root readme is pretty sparse, so this just adds a little context for folks that navigate to it directly, and includes the right links to get started.
> Adding a little more detail to the root readme

- cli/script/cli.ts
- cli/script/command-parser.ts
Fix for 'Running "code-push add app Foo" fails silently'.
> Show help for invalid command combination in CLI

- sdk/script/management/account-manager.ts
Generate a better access key that has the account ID mixed into it.
> Improve Access Key

- cli/script/cli.ts
- cli/script/command-executor.ts
This helps with CLI automation.
> Return Exit Code 1 for failled commands

- cli/script/command-executor.ts
This makes some minor string changes to make the command output a little more consistent/friendly.
> Updating output strings

- cli/script/command-executor.ts
- cli/script/command-parser.ts
Also tidy up cli output strings. Registrations have not been enabled on the server yet, but will be enabled shortly.
> Enable open registration

- cli/README.md
This updates the CLI screenshot to include register, and adds the register command to the docs.
> Register doc

- cli/test/cli.ts
Some of our previous PR's broke the unit tests unintentionally, just a quick fix!
> Fix unit tests

- cli/README.md
Just fixing a minor thing I noticed in the README
> Minor cli readme fix to make the platforms right in the table.

- cli/README.md
> Update heading level for releasing app updates

- cli/definitions/cli.ts
- cli/script/command-executor.ts
- cli/script/command-parser.ts
- sdk/script/management/account-manager.ts
Adding support as per #83. Relies on server-side support which has been implemented!
> Allow rollbacks to an arbitrary release label

- cli/definitions/backslash.d.ts
- cli/definitions/wordwrap.d.ts
- cli/package.json
- cli/script/command-executor.ts
- cli/script/command-parser.ts
Fixes https://github.com/Microsoft/code-push/issues/87
```
geoffreygoh$ code-push release HoleyMoley ./file.js 1.0.0 --description "This\ndescription\nhas\nmultiple\nlines"
Upload progress:[==================================================] 100% 0.0s
Successfully released an update containing the "./file.js" file to the "Staging" deployment of the "HoleyMoley" app.
geoffreygoh$ code-push release HoleyMoley ./file.js 1.0.0 --description "This description\t has tabs" --deploymentName Production
Upload progress:[==================================================] 100% 0.0s
Successfully released an update containing the "./file.js" file to the "Production" deployment of the "HoleyMoley" app.
geoffreygoh$ code-push deployment list HoleyMoley …
```
> Parse backslashes in release description

- cli/test/cli.ts
- definitions/rest-definitions.d.ts
- sdk/script/management/account-manager.ts
Just quickly tidying up unused fields for clarity.
> Remove unused description fields

- cli/README.md
This PR adds a little more detail about the app store version parameter, and makes a few other minor doc tweaks.
> Adding detail for store version

- cli/test/cli.ts
- definitions/rest-definitions.d.ts
- sdk/script/management/account-manager.ts
Copy updated REST definitions from CodePush service.
Fix up test code after making some properties optional.
> Update REST definitions

- cli/script/command-executor.ts
- cli/test/cli.ts
This fixes #102 - Release command should reject binaries.
Also added tests for release command in CLI.
> Release command should reject binaries

- sdk/package.json
> Update superagent and remove 'fs' from 'package.json'

- cli/definitions/cli.ts
- cli/package.json
- cli/script/command-executor.ts
- cli/script/command-parser.ts
- cli/test/cli.ts
- definitions/rest-definitions.d.ts
- sdk/script/management/account-manager.ts
This consumes the changes on another PR for service to add app collaborator support.
> App collaborator CLI

- cli/README.md
This adds the README updates for the new app collaborator feature. I still need to update some screenshots (e.g. to show the new command in the CLI list), but I can do that as a follow up.
> Docs for app collaborators

- cli/script/command-executor.ts
- definitions/rest-definitions.d.ts
- sdk/script/account-manager.ts
- sdk/test/management-sdk.ts
(Merging into 'breaking')
These are a number of small tweaks that need to be made before the breaking changes branch is merged:
- URL encode all REST API inputs (for example, if we want to pass a qualified app name such as `owner@email.com/app`)
- Move access-key generation onto the server
- Reflect structural API changes (PUT requests are now PATCH requests, the /package endpoint is now renamed to /release)
I will be doing a lot of validation today and also be submitting an (optional) PR with the amalgamated collection of breaking changes to merge into master.
> Breaking changes loose ends

- cli/README.md
- cli/definitions/cli.ts
- cli/script/command-executor.ts
- cli/script/command-parser.ts
- cli/test/cli.ts
- sdk/script/management-sdk.ts
E.g.
```
$ code-push deployment clear MyApp Staging
```
> Clear updates associated with a deployment

- cli/test/cli.ts
- sdk/test/management-sdk.ts
Added tests for SDK and CLI for following features
- Promote
- Rollback
- Patch
- Collaborator
- TransferApp
> SDK and CLI Tests

- cli/definitions/cli.ts
- cli/package.json
- cli/script/command-executor.ts
- cli/script/command-parser.ts
- cli/test/cli.ts
> Add --targetBinaryVersion to Patch and Promote

- cli/definitions/cli.ts
- cli/script/command-executor.ts
- cli/script/command-parser.ts
- cli/test/cli.ts
Fixes https://github.com/Microsoft/cordova-plugin-code-push/issues/92.
> Add `build` option to `release-cordova` command

- cli/script/command-executor.ts
> Improve invalid versionName handling

- cli/README-cn.md
- cli/README.md
1. Created `README-cn.md` of Chinese translation.
1. Created a link which is Chinese translation version in `README.md`.
> Add Chinese translation

- cli/script/command-executor.ts
- cli/script/command-parser.ts
This PR simply makes a few small tweaks to the descriptions for some of the access-key commands.
> Command description tweaks

- index.html
I have adjusted the year in the footer because it still says 2015 which is actually not correct :confused:
> Update year in footer

- cli/definitions/cli.ts
- cli/script/command-executor.ts
- cli/script/command-parser.ts
> Allow specifying a build.gradle to the release-react cmd

- cli/script/commands/debug.ts
Replace 'isDeviceAvailable' method with 'getNumberOfAvailableDevices' method,
add new throw statement in case more than 1 attached android device was detected,
because for now there is no ability to specify device for debug
like 'code-push debug android "192.168.121.102:5555"'.
Fix issue #352
> debug: fix android device detection

- cli/script/command-executor.ts
Implement workaround for case when 'build.gradle' file contains several 'android' nodes.
In this case 'buildGradle.android' prop (parsed by 'gradle-to-js' library)
represents array instead of object due to parsing issue in 'g2js.parseFile' method.
Fix issue #349
> command-executor: fix versionName parsing issue

- cli/README-cn.md
- cli/README.md
Fixed mistype in readme docs, see https://github.com/Microsoft/code-push/issues/351 for details.
> Readme Docs For CLI Description Flag Incorrect

- cli/README.md
- cli/definitions/cli.ts
- cli/script/command-executor.ts
- cli/script/command-parser.ts
See https://github.com/Microsoft/code-push/issues/267 for more details
> Add ability to promote a specific label

- cli/README.md
- cli/script/command-executor.ts
Should fix issue https://github.com/Microsoft/code-push/issues/412
> Fixed issue with getting bool values for yargs 6.5.0

- cli/package.json
- cli/script/command-executor.ts
- definitions/base-64.d.ts
- sdk/package.json
- sdk/script/management-sdk.ts
- tsd.json
In addition to the redundancy @max-mironov found in #419, I discovered some more as part of my cryptography audit.
@max-mironov - could you review this one?
> Remove redundant dependencies

- cli/README-cn.md
- cli/README.md
- cli/package.json
> Adjusted readme

- cli/script/command-executor.ts
- cli/test/cli.ts
email, not adding the collaborator immediately. Also made a few unit test
fixes.
> Updated add colloborator message to make clear that it sends an invite

- sdk/README.md
Documentation for the addApp method needed updating.
> Read me fix

- cli/README.md
See https://github.com/Microsoft/code-push/issues/473
> Removed reference to patch for acccess keys

- cli/script/command-executor.ts
Relates to https://github.com/Microsoft/code-push/issues/331
> search for react-native in devDependencies too

- cli/README.md
- cli/script/command-executor.ts
Add ability to use plain integer number for app version
See https://github.com/Microsoft/code-push/issues/377 for details
> Plain integer number

- cli/README.md
> Update cli readme part due to session cmd change

- cli/script/command-executor.ts
As for now we do not consider code signing an experimental feature
> Removed prompt for code-signing release

- package-lock.json
- sdk/package.json
This PR provides fix for https://github.com/Microsoft/code-push/issues/540
The next step will be preparing fix in `react-native-code-push` repo after releasing new version of code-push.
> Update superagent version to fix DoS zip attack

- sdk/script/acquisition-sdk.ts
This PR adds additional error information for the case when zero status code was returned during the request to updateCheck server method.
Related to https://github.com/Microsoft/cordova-plugin-code-push/issues/328
> [Acquisition SDK] Add status.code check for zero value

- .vscode/launch.json
- cli/README-cn.md
- cli/README.md
- cli/definitions/cli.ts
- cli/script/command-executor.ts
- cli/script/command-parser.ts
- cli/test/cli.ts
- gulp/scripts.js
- package-lock.json
- package.json
- sdk/script/acquisition-sdk.ts
- tsconfig.json
> Added --config option for react-release CLI command

- cli/package-lock.json
- cli/package.json
> Bump version

- cli/README.md
made a few changes to make text less confusing
> Fix clear rollback confusing text

- sdk/package-lock.json
- sdk/package.json
- sdk/plugin.xml
* Updated dependencies in code-push/sdk
* Bumped up code-push/sdk version
> Fixed vulnerable and prepare for new release

- sdk/README.md
Fixes a typo in API reference.
> Typo fix in management SDK

- cli/package-lock.json
- cli/package.json
* Bumped version of plist packages.
> Fixed vulnerable dependencies issue in code-push cli

- sdk/package-lock.json
- sdk/package.json
- sdk/plugin.xml
Updating CodePush SDK to 3.0.0-beta
> Update version number to 3.0.0-beta

- sdk/script/acquisition-sdk.ts
- sdk/test/acquisition-rest-mock.ts
Small refactoring code:
* Put the same part of the url strings into a separate variable
> Refactor code

- sdk/package-lock.json
- sdk/package.json
- Update SDK dependencies
- Fix vulnerabilities
> Update SDK dependencies

- .github/workflows/code-push-ci.yml
This PR adds CI configuration that will trigger CI when a pull request to the master is created.
> [CI] Create code-push CI

- src/script/management-sdk.ts
We are migrating to new CodePush service endpoints.
No changes for users.
> Migrate to new codepush service

- src/script/acquisition-sdk.ts
- src/script/management-sdk.ts
- src/test/acquisition-sdk.ts
- src/utils/code-push-error.ts
Fix issue: https://github.com/microsoft/code-push/issues/641
* Add classes for Custom Error
> Specify known errors

- src/script/management-sdk.ts
**Description**: Implement the same approach as `appcenter-cli`
> Change SERVER_URL

- src/script/management-sdk.ts
- src/utils/adapter/adapter.ts
We had several errors with the format of the data sent to the api gateway.
> Fix json parse issue

- package-lock.json
- package.json
Changed included in this release:
- https://github.com/microsoft/code-push/pull/830
> Bump version to 4.2.0

- package-lock.json
- package.json
Changed included in this release:
- https://github.com/microsoft/code-push/pull/838
> Bump version to 4.2.1

- package-lock.json
Fixes vulnerabilities:
- ip - https://github.com/advisories/GHSA-78xj-cgh5-2h22
- minimatch - https://github.com/advisories/GHSA-f8q6-p94x-37v3
> Fix ip and minimatch vulnerabilities

- package-lock.json
- package.json
Changed included in this release:
- https://github.com/microsoft/code-push/pull/846
- https://github.com/microsoft/code-push/pull/843
- https://github.com/microsoft/code-push/pull/845
- https://github.com/microsoft/code-push/pull/842
> Bump code-push version
