microsoft/code-push

cli/package.json

We were missing the license and keyword fields in our package.json, and the author field wasn't consistent with the other repos (e.g. Cordova and React Native plugins)

Cleaning up package.json

---

cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts
sdk/script/management/account-manager.ts

With this PR, users can now promote packages from one deployment to another with the command:
```
code-push promote <appName> <sourceDeploymentName> <destDeploymentName>
```
One common scenario would be to bump a package from the Staging deployment to the Production deployment, perhaps after tests have been done on Staging and the package is ready to be pushed to all of the end users subscribed to the Production deployment.

Add promote deployment functionality

---

cli/script/command-parser.ts

Fix for bug : ```code-push app rm ls``` using our CLI (remove an app named "ls"), the command would fail.
Yargs has some kind of command precedence which checks the usage of the command for an argument in chronological order that it was added to the commands list, so when executing 
'code-push app rm ls' - yargs would interpret it as an ls command and list its usage since we had wrong # of arguments for a ls command. Giving ls, list commands the least precedence enables us to execute rm, remove commands before ls and thereby be able to delete those apps or deployments named 'ls' 'list'.

CLI should be able to remove apps and deployments named ls/list

---

cli/README.md
cli/package.json
sdk/package.json
sdk/plugin.xml

This PR makes the following changes:
1. Updates the CLI screenshot to include the latest command set (e.g. promote)
2. Adds a little more verbiage to the description of "access key add" and promote
3. Bumps the CLI's version to 1.1.0-beta, and updates its SDK dependency to point to 1.1.0-beta (and accept great minor/patch updates)
4. Bumps the management and acquisition SDK's version to 1.1.1-beta

Bumping versions and updating the docs

---

cli/script/command-executor.ts

Calling toString() on the date objects prevents the dates from being truncated when the table is printed.
@lostintangent

Prevent date truncation

---

cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts

And remove the '--verbose'/'-v' options which previously were used to get the package information.

When running the deployment list command, show the package by default

---

cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts
sdk/script/management/account-manager.ts
sdk/test/management-sdk.ts

Here is how it currently looks, I am very open to feedback:
Thoughts:
1. Are we happy with the syntax of the command?
2. The 'description' field is not mandatory when you call the 'release' command, hence I wouldn't be surprised if it was empty most of the time. Brainstorm: Make it a compulsory argument to 'release'? Hide the 'description' column if it is completely empty? Leave it as-is?
3. For deployments with no releases, I'm not sure if the output is confusing. Should I use a custom string?

Add 'deployment view' command to CLI to show release history

---

cli/README.md

Forgot to do this earlier. Two thoughts:
- Is the section this is in a little strange?
- Does the 'history' command actually belong under 'deployment'?

Update README to document the 'deployment history' command

---

cli/package.json
sdk/package.json
sdk/plugin.xml

I'm planning to release an update of the CLI and SDK this afternoon, so this change simply bumps their respective versions.

Bumping the SDK and CLI to v1.2.0-beta

---

cli/script/command-executor.ts

The `login` and `logout` commands currently output multiple log messages, which make it look a little messy. This change consolidates the general "success" message and the add/remove config file success message into a single message, since the two are conceptually the same anyways. I also cleaned up some of the login text that discusses the browser being launched.
Note that the `logout` command will still display two messages, since the removal of the access key also generates a message, but I didn't want to mess with that right now.

Login message change

---

cli/README.md

One of our users filed [a bug](https://github.com/Microsoft/cordova-plugin-code-push/issues/43) on the Cordova side and noticed in his description that it is not entirely clear what the `appStoreVersion` means. So I did a search in our repo for `minimum` and found only this instance.

Minor doc fix.

---

cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts

1. Tidying - use .map() instead of [declare array] -> [forEach] -> [push to array]
2. For the 'app list' command, remove the 'id' column and add a 'Deployments' column with a comma-separated list of deployments
3. Clean up the error message when releasing with a non-semver compliant app store version as in #63
Screenshots:
(Very similar to what actually happened when I was testing)
('app list' command at the top, not sure if we should bother clarifying the error message in the second command)

Cli improvements

---

cli/README.md

This PR adds a little more platform specific detail for the `package` and `appVersion` parameters of the `release` command, that way, the docs are a little more self-serving, without needing to refer to the Cordova/React Native SDK docs in order to understand them fully.

Adding extra platform detail

---

cli/README.md
cli/script/command-executor.ts
cli/test/cli.ts

1. Show package history in chronological order -  when the package history is long, terminals will naturally scroll to the bottom. Hence, we should display the latest packages last for the user's convenience.
2. Do not show Package column for newly created deployments
3. Update README to mention the deployment history limit of 50 releases

CLI Tweaks

---

cli/script/command-executor.ts
sdk/script/management/account-manager.ts
sdk/test/management-sdk.ts

We have been logging server errors in our unzip module, and it is highly likely that the cause is users who are uploading their own .zip files. The CLI will zip up a folder for you if you specify the path, but it will leave single files unchanged.
To address this:
1. Modify the CLI to reject .zip uploads with a helpful error message explaining that the user should specify the directory directly (feedback on the error message welcome).
2. Currently it would be impossible to track whether this fixed the issue or not as older CLI versions will still generate these errors. So, send the CLI version in the User-Agent header with every request so that we can track which CLI versions are generating the errors on the server side (also this is just generally useful for telemetry).

Fix unzipping errors

---

cli/package.json
cli/script/command-parser.ts
tsd.json

Added update-notifier library to give notification when we have a new update to the cli npm package.
This is how it looks:

Code push Cli npm update notification

---

cli/script/command-parser.ts

I tested with pkg passed to the updateNotifier as options object and renamed it to packageJson which broke the behavior. 
Also removed extra require to use packageJson in version for ascii art.

Fix to assign packageJson to pkg.

---

cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts
sdk/script/management/account-manager.ts

This feature allows you to undo your most recent release if you have shipped a broken or unintended update. It is equivalent to performing a new release with the same package contents and metadata as the release preceding your most recent one.
For performance and simplicity reasons this feature is implemented on the server side, with the implementation here being a simple POST request. In future, there is quite a lot of duplication and boilerplate in this project that can probably be refactored out (not the highest priority right now).

CLI rollback feature

---

cli/README.md
cli/package.json
sdk/package.json

Add documentation on rollback command

---

sdk/script/management/account-manager.ts
sdk/test/management-sdk.ts

Trying to move us towards writing the deploymentKey directly onto the deployment object, and phasing out the /deploymentKeys REST endpoints for better perf and code clarity.

Remove dead deploymentKey methods

---

definitions/rest-definitions.d.ts
sdk/script/acquisition-sdk.ts
sdk/test/acquisition-rest-mock.ts
sdk/test/acquisition-sdk.ts

This allows the server to use the label to figure out the current version of the package instead of searching the history for the packageHash.

Attach label to updateCheck requests

---

cli/script/command-executor.ts

You can still see the hashes using the "--format json" flag, if needed.

Remove package hashes in "deployment list" command

---

cli/README.md

This PR improves our docs in the following ways:
1. Documents the new `--targetRelease` parameter of the `rollback` command.
2. Documents the ability to include newlines in the `--description` parameter of the `release` command.
2. Includes more description about how the `mandatory` flag of a release is handled by the server.
3. Includes more description about how the `promote` and `rollback` commands work.
4. Includes more prescription about creating separate CodePush apps when targeting both Android and iOS
5. Includes more description about how to think about deployments.
6. Includes more prescription about how to use `Staging` for testing updates before releasing to `Production.
7. Includes an example of how to prepare/release a React Native iOS app that uses assets

Doc updates

---

cli/package.json

Bumping the CLI version so we can publish the `description` regression fix to NPM.

CLI version bump

---

definitions/rest-definitions.d.ts
sdk/script/acquisition-sdk.ts
sdk/script/samples/typescript-acquisition.ts
sdk/test/acquisition-sdk.ts

Goal: To allow client devices to better report the status of their update acquisition (whether an update is successfully installed or rolled back, which update is the client running). The eventual goal is to allow developers to see this data from the CLI so that they can better manage their updates!
This PR: Mainly includes changes to the acquisition SDK
- The config passed to the constructor for the AcquisitionManager must now include the native app version and a unique ID for the client (e.g. device GUID).
- The reportStatus() method takes now two optional parameters - the current installed package, and the status. If both are not specified, it will be reported to the server that the app is running the version shipped with the app store binary. If both are specified, then depending on …

Report Acquisition Status

---

definitions/rest-definitions.d.ts
sdk/script/acquisition-sdk.ts
sdk/test/acquisition-rest-mock.ts
sdk/test/acquisition-sdk.ts

Small change. In the cordova/RN SDKs, if the install mode is ON_NEXT_RESTART, there could be a large gap of time between the time a package is downloaded and the time a package is finally installed. This adds a new acquisition API, "reportStatusDownload" to be used to report to the server whenever the client downloads a package, and will be called the moment a package is downloaded.

reportStatusDownload

---

cli/script/command-parser.ts

Updating the names and examples for the `release` command to be a little more intuitive.

Renaming some of the release parameters

---

cli/package.json
cli/script/command-executor.ts

This simply removes the CLI's dependency on the `try-json` library, which addresses the warning users see when installing the CLI (as reported by #96).

Removing try-json dependency

---

cli/package.json
sdk/package.json
sdk/plugin.xml

Bumping the CLI and SDK to `1.5.0-beta` in order to prepare for the metrics release.

Bumping CLI and SDK versions

---

cli/script/command-executor.ts

Fixes a tiny bug with the "%" symbol not showing up in the case where the active percentage is 100.

Fix 100% bug

---

sdk/package.json
sdk/plugin.xml
sdk/script/acquisition-sdk.ts

Replacing uses of the identifier `package` since that is a reserved keyword, which Babel will reject when bundling this file as part of a React Native app. I'm also bumping the version so that we can release this update to NPM.

Renaming 'package' parameters

---

cli/script/command-executor.ts

This PR simply changes the names of two headers in the deployment and release history, and ensures that the number of pending installs is greater than zero before showing it. For the later, we should investigate why this number would become negative, but in the meantime, it seems semantically correct to explicitly verify that we want a positive number anyways.

Release table header changes

---

cli/script/command-executor.ts
cli/test/cli.ts
definitions/rest-definitions.d.ts
sdk/script/account-manager.ts
sdk/test/management-sdk.ts

(merging into 'breaking' branch)
This mirrors an upcoming breaking change on the server. This little tweak simplifies our code base and gives us a modest perf improvement.

Remove deploymentKey method from SDK and fetch the key off the Deployment object

---

cli/README.md

This introduces basic docs for the new metrics feature as well as for the new `--displayKeys` flag for the `deployment ls` command.

Doc updates to include metrics

---

cli/script/command-executor.ts

This PR simply adds a new message to the `Update Metadata` column in the table output by `deployment ls` for deployments that haven't had an update released to them yet. It is consistent with the message that we display in the new `Install Metrics` column when a specific deployment/release hasn't had any install reports yet.

Adding no updates message

---

definitions/rest-definitions.d.ts
sdk/package.json
sdk/script/acquisition-sdk.ts
sdk/test/acquisition-sdk.ts

Change the Acquisition SDK to allow clients to send previous version deployment key and label as part of the client state.

Metrics SDK Changes

---

cli/README.md

This PR simply adds mention of our new assets support on Android and updates the names of the parameters in the `release` command.

Updating docs for Android asset support

---

definitions/try-json.d.ts
sdk/package.json
sdk/script/account-manager.ts

This was originally intended to be done later as part of productizing the SDK, however this quick PR simplifies my other work too.
Changes:
1. Clean up/de-deduplicate all of the boilerplate. The number of lines is halved and it's much more readable. I've also found out that we have some inconsistencies with how we handle response bodies in POST requests.
2. Convert everything to use template strings
3. Remove try-json dependency

Tidy up SDK

---

cli/package.json
sdk/package.json
sdk/plugin.xml

The new collaborator feature ships with this version. 1.6.0-beta.

Bump versions for cli, plugin and sdk

---

cli/script/command-executor.ts
cli/test/cli.ts
definitions/rest-definitions.d.ts
sdk/script/account-manager.ts
sdk/test/management-sdk.ts

(Merging into 'breaking'. On the diff tab, add '?w=1' to the URL to ignore whitespace changes)
Note that the issue of disambiguating duplicate apps by email is not explicitly addressed here. I will address this in a subsequent review, but I expect that it will be a matter of URL encoding the '<email>/appName' chunk and then decoding it on the server.

Move name resolution logic out of the CLI

---

cli/script/command-parser.ts

This simply sorts the list of commands so that the output of the `code-push` command are displayed appropriately.

Sorting command list

---

cli/script/command-executor.ts
cli/test/cli.ts

(Merging into 'breaking')
The server now accepts qualified app names as input and also sends them as output where appropriate, so that this logic does not need to be performed by clients.
This will be the last set of breaking changes on the client (I didn't realize I needed to do this when I sent the wrap-up PR yesterday)

Rely on server for generation of qualified app names

---

cli/script/command-parser.ts
sdk/script/account-manager.ts

Just a quick fix. The CLI will now point to `https://codepush-management.azurewebsites.net`.

In the CLI, use the server URL defined by the SDK

---

cli/README.md
cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts

To "index.android.bundle", to match RN's default https://github.com/facebook/react-native/blob/master/local-cli/generator-android/templates/src/app/react.gradle#L5

[release-react] Change default jsbundle file name for android

---

cli/README.md
cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts

Firstly, reflect the upcoming server change by removing the concept of a base 64-encoded 'access token', which was unnecessary. We consistently use access keys now.
Secondly, ignore the `serverUrl` property in the session file. The reason is that many users will have session files on disk that point to `https://codepush.azurewebsites.net`, whereas in the upcoming release the CLI will communicate with `https://codepush-management.azurewebsites.net`. For these users, the server would erroneously send them a message asking them to upgrade their CLI (even if they're already on the latest!) For debugging purposes, I've instead added a `customServerUrl` property that only gets written to disk if explicitly specified (the URL will be pulled from the SDK otherwise).

Login session file changes

---

cli/README.md
cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts

This is especially important for the HockeyApp integration, as HockeyApp customers will be logging in with their HockeyApp API key, and need it to persist across multiple sessions.
In future it would make sense to store metadata about how the access key was generated on the server, but regardless of whether we do that it makes sense to me to do this particular piece on the client so that we don't need to consult with the server.

Do not remove the access key on logout if we logged in via '--accessKey'

---

cli/README.md
cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts

Allow updates to target a range of binary versions using semver range expressions https://github.com/npm/node-semver#advanced-range-syntax. Added an extra option in the `release-react` command to allow users to override the target binary range value specified in the app metadata. Added some tests for the new changes.
Updated the docs to reflect this new behaviour.

Let updates target a range of binary versions

---

cli/README.md
cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts

Just a super quick, 5min change that exposes the --dev option to the release-react command since I figured it would be useful for my demo.

Expose --dev option to release-react

---

cli/package.json
sdk/package.json
sdk/plugin.xml

This simply bumps the management SDK and CLI versions in preparation for our upcoming release. The current `code-push` dependency that CLI has is incorrect, since it would fail to work correctly when using the `1.6.0-beta` release.

Version bump

---

cli/script/command-executor.ts
cli/test/cli.ts
sdk/script/management-sdk.ts

Infer the hostname internally within the method, and make the description field compulsory (in TypeScript at least).

Change the SDK's addAccessKey() method to be more consumable

---

README.md
cli/README.md
sdk/README.md

We can expand on this later, but this provides the basic getting started and reference docs for users wanting to take advantage of the new Node.js management SDK.

Initial checkin for SDK readme

---

cli/README.md
sdk/README.md

This PR simply adds docs for the new clear deployment functionality in the CLI and management SDK.

Small doc tweaks

---

cli/README.md
cli/definitions/cli.ts
cli/package.json
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts
cli/test/resources/TestApp/config.xml

Adds release-cordova command.
code-push release-cordova <appName> <platform>
This command will call cordova prepare and publish a release, inferring binary version from config.xml and update package from the current directory.
It will fail if the current directory does not contain a config.xml, or if the specified platform was not added to the project using the Cordova CLI.
@lostintangent @silhouettes @shishirx34 @geof90

Add release-cordova

---

cli/package.json

The gradle-to-js npm module will parse a versionName of "1.0" as the Javascript number "1". With that, we have no way to tell whether it has a minor version or not. I forked the project and changed the parser to always return strings as the obvious but workable solution for our purposes. https://github.com/geof90/gradle-to-js/commit/ccd3362ad227203319f799dda03a6db3577c56a8

Gradle parsing issue

---

cli/script/command-executor.ts

This resolves #161 by ensuring that the ZIP generated by the `release` command is always deleted, regardless if the release fails (e.g. because the server rejected an identical release).

Deleting release zip on erorr

---

cli/package.json
cli/script/command-parser.ts
sdk/package.json
sdk/plugin.xml

This PR enables rollout parameter to specify a `%` sign as a suffix. 
Also bump SDK and CLI version for npm release.

Allow percent sign in rollout parameter and bump version

---

cli/README.md

Updates the CLI docs to include a new TOC, as well as include details for the new `rollout` parameter, `patch` command, and expanded `promote` command. I also took it upon myself to organize the three release variants a little bit.

Updating docs

---

cli/script/command-executor.ts

Adds verbose flag to cordova prepare command.
Pipes stdout and stderr to console.
@lostintangent @silhouettes @geof90 @shishirx34

Pipe Cordova Prepare output

---

cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts
definitions/rest-definitions.d.ts

This PR allows users to disable (or subsequently re-enable) a particular release using the `code-push patch` command. It also makes the CLI throw an error if no properties are specified for update when using that command.
It also changes the `code-push deployment history` command to indicate whether a particular release is disabled.

Disable releases

---

cli/README.md
cli/definitions/cli.ts
cli/package.json
cli/script/command-executor.ts
cli/script/command-parser.ts
sdk/package.json
sdk/script/acquisition-sdk.ts
sdk/test/acquisition-sdk.ts

This change allows users to specify the "disabled" metadata when releasing or promoting an update.
Also combined this PR with https://github.com/Microsoft/code-push/pull/174, which configures the acquisition SDK to forward the `shouldRunBinaryVersion` flag sent by the server to notify client plugins to trigger a rollback to the binary version if needed.

Add "disabled" metadata for promote and release + forward shouldRunBinaryVersion flag from server

---

cli/README.md

This PR adds more details to the `release-react` and `release-cordova` commands, including examples of how they simplify releasing updates as compared to the "vanilla" `release` command.

Adding more detail to the release-* commands

---

cli/script/command-executor.ts

This addresses and issue with release-cordova on Windows.
spawn can't execute bat/cmd files, which is how npm packages are executed on Windows.
Exec doesn't care, so swap to using this.
@shishirx34 @silhouettes @geof90 @lostintangent

switched process call to exec instead of spawn

---

cli/script/command-parser.ts

This is a quick tweak purely for the sake of internal testing, as custom server URL's are not needed by end users.
A major annoyance for the longest time when using Git Bash on Windows is that, due to path translation, a URL like `http://localhost:3000` passed on the command-line ends up as `http:\localhost:3000` by the time it ends up in our CLI. This just compensates for that by translating it back.

Compensate for git bash on Windows when parsing custom server urls

---

cli/test/cli.ts

This PR fixes the release-cordova tests.
These were broken by the change to using exec instead of spawn (addressing the issue of running this command on Windows).
@silhouettes @shishirx34 @lostintangent @geof90

Fix release-cordova tests

---

cli/README.md
cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts

This PR introduces a new `code-push whoami` command which allows users to determine if they are already logged in, and if so, with which e-mail address. This command mirrors the equivalent in the NPM CLI.

Adding whoami command

---

cli/README.md
cli/script/command-executor.ts
definitions/rest-definitions.d.ts

This PR enhanced the `whoami` command by also displaying the list of identity providers that your account is linked with.

Adding linked providers to whoami

---

definitions/rest-definitions.d.ts
sdk/package.json
sdk/plugin.xml

Updating the SDK version to reflect change of object structure for package.
Although none of the clients use this change, keeping the definitions in sync with the server change.

Update rest definitions for improving diffs

---

cli/package.json

Bumping the minor version to release the new Windows support in the `release-react` command and the new `--build` flag for `release-cordova`.

Bumping version

---

cli/package.json

Hello world!
@geof90 has kindly contributed his improvement into the main repo, and I thought that I'd let you know that the changes are now available in version `0.1.0`. You can merge this PR if you feel like jumping on the NPM registry track again, or just close if you don't.  :-)
Have a great weekend!

Bump gradle-to-js to version 0.1.0

---

cli/package.json
cli/script/command-executor.ts

This PR fixes #219 by simply checking for the presence of both the `cordova` and `phonegap` CLIs in order to prepare/build the project. Note that we don't need to worry about supporting `ionic`, since it uses `cordova` under the covers, and therefore, a machine with `ionic` installed, but not `cordova`, wouldn't actually work. Only `cordova` and `phonegap` are "standalone" tools.

Adding PhoneGap support to release-cordova

---

cli/script/command-executor.ts

This PR fixes [react-native-code-push#329](https://github.com/Microsoft/react-native-code-push/issues/329) by simply lowercasing the "ios" directory we use when trying to auto-detect the app's binary version. The React Native templates have always generated a lowercased "ios" directory, and therefore, we should have already been using this. On Windows and most OS X machines, it wouldn't matter either way, but as noted by the bug, on Linux machines, case  matters, and therefore, this PR enables us to work across all platforms by default. 
If someone were to change the "ios" directory to be named "iOS" or "IoS" (or whatever), and run `release-react` on a machine with a case-sensitive file-system (e.g. Linux), this PR wouldn't address that scenario. However, I don't believe this is a common …

Lowercasing "ios" directory in release-react

---

cli/test/cli.ts

Fixes a broken test by previous release which modified the message for release-cordova.

Fix modified message for CLI tests

---

cli/script/command-parser.ts

Fixes #220 - empty option for deploymentName yargs parameter calls into the wrong route.

Add yargs check for missing deployment name.

---

cli/package.json
sdk/package.json
sdk/script/acquisition-sdk.ts
sdk/test/acquisition-sdk.ts

This PR reverts https://github.com/Microsoft/code-push/commit/812218858b1afc170d1addc2c625ede267d53e75 because it breaks the Cordova plugin which blindly assumes that a returned object is an update.

Revert 8122188

---

cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts
sdk/script/management-sdk.ts
sdk/script/types.ts
sdk/test/management-sdk.ts

(Merging into "access-key-changes" branch)
This PR:
- Adds the ability to list sessions. 
- `access-key ls` will only show access keys that are created via `access-key add`, and will show the name of the key, the time it was created, and the expiry.
- `session ls` will only show keys that are created via the normal login process, and will show the name of the machine associated with the session and the time it was created.
- Adds the ability to remove sessions by "machine name"
- Automatically removes the cached credentials on the temp directory if they are no longer valid (expired, etc).
- Fixed a test with the Management SDK - the statusCode was not being propagated in the returned error. Hilariously, the "methods reject the promise with status code info when an error occurs" test did …

code-push session ls + rm

---

cli/README.md
cli/definitions/cli.ts
cli/definitions/parse-duration.d.ts
cli/package.json
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/test/cli.ts
definitions/rest-definitions.d.ts
sdk/package.json
sdk/script/management-sdk.ts
sdk/script/types.ts
sdk/test/management-sdk.ts

This PR:
- Adds the ability to specify an expiry to access keys. If unspecified, keys will be created with a default expiry (60 days) on the server side.
```
$ code-push access-key add "Temporary key" --maxAge 5m
Successfully created a new access key "Temporary key": NnPx5-nmPnooZeMJygxmcqUd6wptVJx1XOClg
(Expires: Wed Jun 01 2016 16:59:19 GMT-0700 (PDT))
```
- Adds the ability to edit the name and expiry of your access keys.
```
$ code-push access-key edit "Old name" --name "New name" --maxAge "7h 15m"
Successfully renamed the access key "Old name" to "New name" and changed its expiry to Thu Jun 02 2016 00:21:43 GMT-0700 (PDT).
```
- Adds the ability to see the expiry of all your keys. In an upcoming server change, the server will no longer show the actual key strings anymore when the CLI …

Access key changes

---

cli/definitions/cli.ts
cli/package.json
cli/script/command-executor.ts
cli/script/command-parser.ts
cli/script/commands/debug.ts

This PR introduces a new `debug` command to the CLI which allows you to easily view the CodePush debug logs for a running Android or iOS app. This provides an easier on-boarding experience when users need to diagnose what may be going wrong with our plugin, and doesn't require them to use (or learn) a separate tool in order to do it (e.g. Chrome console, OS X console, Xcode console, ADB logcat).
*NOTE: This doesn't currently support iOS devices, but we can add that later.*

Adding debug command

---

cli/script/commands/debug.ts

In my attempt to display a platform-agnostic view of the CodePush logs via the new `code-push debug` command, I forgot to strip the source URL suffix that the Cordova Android platform adds to each log message. This PR simply introduces a new capability to each debug platform that allows them to perform any platform-specific processing on each log, which allows them to "clean" them up before being displayed to the end user. The beauty of this is that all of the logs look the same, regardless if its Cordova, React Native, Android or iOS.

Stripping Android Cordova suffix

---

cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts

This addresses #207 by adding two new optional parameters to the `release-react` command: `plistFile` and `plistFilePrefix`. The latter allows simply augmenting the existing behavior in situations where you have created per-environment plist files (e.g. `DEV-Info.plist` vs. `PROD-Info.plist`), and you just need to let CodePush know which prefix you want it to use in order to infer the correct app version of your update. This allows devs a bit more flexibility in how they organize their app's config, without requiring them to drop down to explicitly specifying the `--targetBinaryVersion` parameter when calling `release-react` (which feels like a failure on the command's part).
The `plistFile` parameter is for situations where your plist file is in an entirely arbitrary location and/or …

release-react plist customizations

---

cli/package.json
cli/script/command-executor.ts

This PR addresses https://github.com/Microsoft/react-native-code-push/issues/353. It enhances the existing Android support in the `release-react` command by allowing an app to reference a Gradle property as the value of the `versionName` setting in their `build.gradle` file, as opposed to only being able to specify a string literal. This change allows referencing the variable with or without the `project.` prefix, and allows the variable to be defined in either the app or project-wide properties file for added flexibility.
**Example build.gradle file:**
```groovy
android {
defaultConfig {
versionName VERSION_NAME
}
}
```
**Corresponding gradle.properties file:**
```properties
VERSION_NAME=1.2.3
```

Adding gradle.properties support to release-react

---

cli/script/command-executor.ts

This PR improves the `release-react` command in the following ways:
1. It adds a new "logging step" which explicitly displays the value that is inferred, and from which file, when auto-detecting the target binary version. This way, it's clearer what exactly the command is doing.
2. Updates the new `--plistFilePrefix` parameter by auto-appending a "-" if the provided value doesn't already end in a separator (currently a period or hyphen). In practice, 100% of the files I've seen use a hyphen as a separator, so this change simply conforms to the common convention.
3. Makes various improvements to the existing log messages
After this PR, I think the `release-react` command is in a pretty awesome state. However, I can imagine the need for us to add a new `--gradlePath` parameter to allow …

Improving release-react

---

cli/script/command-executor.ts
cli/test/cli.ts
definitions/rest-definitions.d.ts

use the fact that deployment names are now stored in the rest app object

---

cli/script/command-parser.ts

This is a fix for #286, where an app store version specified on the command line like `1.10` would be converted by yargs to a number, i.e. `1.1`. This only applies to non-hyphenated parameters, and not flagged options, where the type is explicitly specified.
As this is somewhat unexpected, I've turned this number conversion off for all non-hyphenated arguments. For our existing commands, I've checked that all non-hyphenated arguments are strings, so there should be no side effects.

Turn off implicit number conversion of non-hyphenated yargs arguments

---

cli/package.json

This is to include [this change](https://github.com/ninetwozero/gradle-to-js/pull/3) that allows gradle files that include function definitions to be parsed correctly.

Update gradle-to-js dependency and bump package.json version

---

cli/script/command-executor.ts
sdk/script/management-sdk.ts

1. Fix the error message when there is a network issue (https://github.com/Microsoft/react-native-code-push/issues/124)
1. Improve error messages when you log out, and when server authentication fails. This should further mitigate a lot of the confusion around expired access keys previously reported on slack and elsewhere.
1. Add error codes to the SDK, so that consumers can better handle errors

Better error messages

---

cli/script/command-executor.ts
sdk/script/management-sdk.ts
sdk/test/management-sdk.ts

Perform a separate call to server to check for authentication before making an upload release file call.

Fix check authentication

---

sdk/script/management-sdk.ts

- Need to remove the `packageFile` and not the File object, otherwise the temporary `.zip` file sticks around after a `release` command.
- @silhouettes

Fix failure to unlink temporary file

---

cli/README.md

To avoid issues like this one https://github.com/Microsoft/cordova-plugin-code-push/issues/189 “App Management” chapter probably should pay attention on the fact, that “using single app both for iOS and Android may cause installation exceptions due to CodePush update (zip package) produced for iOS may have different content than update produced for Android”.

cli_readme: improved “App Management” chapter

---

cli/README.md
cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts

“outputDir” parameter is used to specify the path where bundle and sourcemap should be written.
Relate #376

code-push-cli: implement “outputDir” parameter

---

cli/package.json

`0.2.5` package version contains fix of following issue:
> parsing issue occurs in case `build.gradle` file contains several `android` closures
> https://github.com/ninetwozero/gradle-to-js/issues/4
Fix https://github.com/Microsoft/code-push/issues/349

package: update `gradle-to-js` package version to `0.2.5`

---

cli/script/command-executor.ts
cli/test/cli.ts

Example usage:
```sh
env NODE_ARGS="--max-old-space-size=4096" code-push release-react APP_NAME ios
```
I couldn't find anywhere else secondary node processes are being spawned, but happy to add this functionality to those places as well.
Ref #215

Allow setting of node binary arguments via NODE_ARGS env var

---

cli/script/command-executor.ts

Make the message more severe than it currently for app rm and deployment rm commands

Make the prompt defaults to 'no' if no input is entered

---

cli/script/command-executor.ts
cli/test/cli.ts

This validation helps to save about 1 minute or more in case user has typed wrong app name.
In case app (or deployment) does not exist the error will be shown with the following outputs: 
`App "myapp" does not exist` or `Deployment "mydeployment" does not exist`.
So user have not to wait until code-push update is ready for upload.
Relate https://github.com/Microsoft/react-native-code-push/issues/706

command-executor: check for app and deployment exist before releasing an update

---

cli/README.md

Due to https://github.com/npm/node-semver#prerelease-tags ranges only works for non pre-release versions.
If you want to update a version with pre-release tags, then you need to write the exact version you want to update (`1.12.3-beta` for example)
Relates to https://github.com/Microsoft/code-push/issues/335

cli-readme: ranges only works for non pre-release versions

---

cli/README.md
cli/definitions/cli.ts
cli/script/command-executor.ts
cli/script/command-parser.ts

See https://github.com/Microsoft/code-push/issues/392 for details

Add  build type option to release cordova command

---

cli/script/command-executor.ts

(Add ?w=1 to the end of the URL in the file view tab to ignore whitespace changes)
The unit tests pass `command.label` as `undefined` instead of `null`, which means the output of the `promote` command will be wrong in the unit tests.
@max-mironov, @sergey-akhalkov - this is not a customer-facing issue so it's not a big deal at all, and it's my fault for not mentioning it, but please make sure you run `gulp test` before you submit PR's, and maybe even add test cases if you can. This applies to the CLI and service repos only, as the test framework in the SDK repos is incomplete. Also, please review this change, and I can merge it after.

Small tweak to fix unit tests

---

cli/script/command-executor.ts
cli/script/command-parser.ts

I created a proxy-to-mobile-center branch in the CLI code, corresponding to the proxy-to-mobile-center branch in the service, for changes that go live post Mobile Center migrate. This PR on that branch is for the first batch of CLI updates, removing these features deprecated post Mobile Center integration:
code-push app transfer
code-push collaborator
code-push session
access key rename / change TTL
showing auth types for whoami

First CLI update for Mobile Center integration

---

cli/script/command-executor.ts

Use \"code-push deployment list\" to view any existing deployments and \"code-push deployment add\" to add deployment(s) to the app
if the app doesn't exist. We only show it now if the deployment doesn't exist.

Fixed to not show this additional error text

---

cli/README.md

Small fix for https://github.com/Microsoft/react-native-code-push/issues/1001

Fix wrong code signing link in docs

---

cli/README.md

Small fix for Microsoft/react-native-code-push#1001

Fix wrong code signing link in android docs

---

cli/script/command-parser.ts
cli/script/release-hooks/signing.ts

In preparation for code-signing support for cordova, the code-push cli should support the -k option for the `release-cordova` command as well.

add privateKey support for release-cordova

---

cli/script/release-hooks/core-release.ts
sdk/README.md
sdk/script/management-sdk.ts

This PR updates the return type of the management sdk `release` method, to return a `Promise<Package>` instead of a `Promise<void>`.
To conduct some code push automation part of a project, we need to get back the `label` that was created following a deployment through `release` method code. Unfortunately, because the `release` method is returning a `Promise<void>` we don't get this information back, even though it is contained within the successful server response.
Looking at the response payload we get back from the server following a successful deployment through `release` method call,
```json
{
"package": {
"isMandatory": true,
"appVersion": "1.0",
"packageHash": "3fc3828e674d8903fdc7c0dd4924938946f6b76314e1317cdef10fa946b89060",
"blobUrl": …
```

Update return type of management sdk release method

---

sdk/README.md
sdk/script/management-sdk.ts
sdk/test/management-sdk.ts

In continuation to my previous PR https://github.com/Microsoft/code-push/pull/533, this PR updates the return type of the SDK `promote` method to return the `Package` object part of the server response instead of returning `void`.
Part of an ongoing project, calling in the CodePush SDK, we need the data resulting from the promotion.
It seems that the server call associated to `promote` will always return a body with a package object resulting from the promotion. Even the test was mocking a response with a package, so it seems that the server will always return a package response body in case of success.
If not (I'm doubting it), what could be done is changing the return type to `Promise<Package|void>` and changing the `expectResponseBody` back to false, and return the response Package if …

Update return type of SDK promote method 

---

cli/package-lock.json
cli/package.json
cli/script/command-executor.ts

relates to https://github.com/Microsoft/code-push/issues/544

fix issue w/ outputDir in case of using code-signing

---

assets/stylesheets/ga.style.css

The "Visit App Center" button had a break line on Firefox

Fix button break line on Firefox

---

cli/README.md

*Issue*: Docs says `app store version` where should be `binary version` as it is more understandable for users.
*Solution:* Replaced app store version with binary version in docs.
Related issue: https://github.com/microsoft/code-push/issues/605

Replaced app store version with binary version in docs

---

definitions/rest-definitions.d.ts
sdk/script/acquisition-sdk.ts
sdk/test/acquisition-rest-mock.ts
sdk/test/acquisition-sdk.ts

* Update types of `UpdateCheckRequest`, `UpdateCheckResponse`, `DeploymentStatusReport`, `DownloadReport`.
* Update logic and test with new names.
* Small code style refactors.

Update acquisition sdk to work with new service

---

sdk/package-lock.json
sdk/package.json
sdk/script/acquisition-sdk.ts
sdk/test/acquisition-rest-mock.ts

In order to use the new CodePush API service, we need to make sure to use the correct public API prefixes for CodePush.
The changes in this pull request update the paths in the SDK code as well as the tests and bump the version of the SDK to 3.0.0-beta.1.

Update public acquisition api paths in SDK

---

sdk/script/management-sdk.ts

In order to keep the management SDK working as expected, we decided to switch it back to the legacy endpoint. We will work on deprecating the old CodePush services soon and will pick up the topic when we are working on this feature.

Revert back to legacy api for management calls

---

package-lock.json
package.json
src/script/management-sdk.ts
src/test/management-sdk.ts

Due to the use of Q.Promise in the code-push SDK, we are missing typing. We should replace Q.Promise with es5 Promise, which allows us to save types in the module.

Replace Q.Promise with es5 Promise

---

package-lock.json

Resolves the _critical severity_ alert from Dependabot.

Bump vm2 from 3.9.3 to 3.9.5 in package-lock.json

---

package-lock.json
package.json

This PR resolves the Moderate level alert (we update mocha to the latest version):

Bump nanoid to 3.2.0 via mocha

---

package-lock.json
package.json

This PR resolves the High level alert (we update shx to the latest version):

Bump shelljs to 0.8.5 via shx

---

src/utils/adapter/adapter.ts

If `isMandatory` is set to `false` during a promote and the source deployment has `isMandatory` as `true`, the resultant deployment will have `isMandatory` set to `true` because of the way the check was implemented.  
This PR fixes that behaviour and ensures the right flag is set.

fix: Mandatory flag wasn't set correctly on promote

---

package-lock.json
package.json

`superagent` version warning occurs during `reaction-native-code-push` configuration.
---
Author: [@seungminio](https://github.com/seungminio)
This is a copy of https://github.com/microsoft/code-push/pull/801 with updated package-lock.json file.

Bump superagent 6.1.0 to 8.0.0

---

.github/scripts/check-for-declaration.ts
.github/workflows/code-push-ci.yml
package.json

1. Bumped `ts` version  to `5.1.6`
2. Added CI check for declaration file check
3. Added a script to check before releasing to npm `npm run check:release` 
NOTE: Please include the command `npm run check:release` in your npm release workflow as this will check for declaration files

fear: bumped `ts` version and added check for `.d.ts` files

---

package-lock.json

This PR fixes [ip vulnerability](https://github.com/advisories/GHSA-78xj-cgh5-2h22) by updating it to fixed versions.
[AB#104354](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/104354)
https://github.com/advisories/GHSA-78xj-cgh5-2h22

Update ip to v1.1.9 and v2.0.1 to fix the vulnerability

---

.github/workflows/code-push-ci.yml

Mac images was updated on agents to use arm type. Our build is now failing on installing node 14.
Set macos-13 to fix the issue.

Fix CI by setting macos 13 on github actions

---

src/script/acquisition-sdk.ts
src/test/acquisition-rest-mock.ts
src/test/acquisition-sdk.ts

Implemented feature for stopping api calls from being sent after unsuccessful response. This behavior is aligned with other appcenter SDKs. Disabling of api calls occurs only per session after first failed request.
[AB#107980](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/107980)

Disable api calls

---

package-lock.json
package.json

Changed included in this release:
- https://github.com/microsoft/code-push/pull/851

Bump version to 4.2.3
